SELECT HISTORY_ID,
       CASE 
       WHEN RENTAL_DATE < 7 THEN ROUND(DAILY_FEE * RENTAL_DATE,0)
       ELSE ROUND(DAILY_FEE * (1 - DISCOUNT_RATE/100) * RENTAL_DATE,0)
       END AS FEE
FROM (SELECT HISTORY_ID, CAR_ID, DATEDIFF(END_DATE,START_DATE) + 1 AS RENTAL_DATE,
     CASE WHEN DATEDIFF(END_DATE,START_DATE) + 1 BETWEEN 7 AND 29 THEN '7일 이상'
     WHEN DATEDIFF(END_DATE,START_DATE) + 1 BETWEEN 30 AND 89 THEN '30일 이상'
     WHEN DATEDIFF(END_DATE,START_DATE) + 1 >= 90 THEN '90일 이상'
     END AS DURATION_TYPE
     FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY) AS HR
JOIN CAR_RENTAL_COMPANY_CAR C
ON C.CAR_ID = HR.CAR_ID
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
ON P.DURATION_TYPE = HR.DURATION_TYPE AND P.CAR_TYPE = C.CAR_TYPE
WHERE C.CAR_TYPE = '트럭'
GROUP BY HR.HISTORY_ID
ORDER BY FEE DESC, HISTORY_ID DESC